custom_dir = ""
custom_output = None
custom_name = None
general_graph_type = ["foil", "altered", "signed"]
database_url = "https://api.scryfall.com"
storage_method = None
general_index = False
cleanup = True
# fetch_rate = None
